### PR TITLE
memory leak fixed, some small issues fixed

### PR DESCRIPTION
**Pull request by normaluser**
translated comments...

### CODE REVIEW

**Comment by pan-te** [comment]
Hi.
As you may noticed, this code was written, when I was at high school. It was made as an exercise, so I'm very surprised, and glad, that someone dived into it and found some issues. I'll merge it, but with one remark: the way code was changed makes changes' tracking difficult.
Regards

**Comment by normaluser** [comment]
Hi, next week i will fix the origin source and i will start a second pull
request with the origin code written by you. Is there a possibility to ask
you some questions about the code? some background infos not mentioned in
the comments of the source...   regards Uli

pan-te ***@***.***> schrieb am Do., 28. Sept. 2023, 00:04:

**Comment by pan-te** [comment]
Of course. I'll be glad to help

**Comment by normaluser** [comment]
hello pan-te,

i want to point out that at last i fixed the biggest issue of the code:
the coordinates (of the player and of the walls) has to be truncated
and not rounded!
Thanks.

greetings
Uli

**Pull request merged**
